spring.application.name=ai-as-agent
spring.ai.ollama.chat.enabled: true
spring.ai.ollama.chat.options.model: qwen2.5-coder:0.5b
spring.ai.ollama.chat.options.temperature: 0.8
server.port=8085
logging.level.root=DEBUG
spring.ai.chat.client.observations.log-prompt=true
spring.ai.chat.client.observations.log-completion=true
logging.level.org.springframework.ai.chat.client.observation=DEBUG
logging.level.org.springframework.ai.chat.observation=DEBUG
